apiVersion: v1
kind: ConfigMap
metadata:
  name: pmc-cm
  labels:
    app: {{ include "pmc.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
      "host-ip": "{{ .Values.config.mimirEndpoint }}",
      "timeout": 20,
      "plugin-dir":"cwd",
      "service-port":"{{ .Values.config.servicePort }}",
      "clusters": [
      {{- range $j, $cluster := $.Values.config.clusters }}
        {{- if lt (add1 $j) (len $.Values.config.clusters) }}
        {
          "clusters-provider":"{{ $cluster.provider }}",
          "clusters":
          [
            {{- range $i, $c := $cluster.clusters }}
            {{- if lt (add1 $i) (len $cluster.clusters) }}
            "{{$c}}",
            {{- end }}
            {{- if eq (add1 $i) (len $cluster.clusters) }}
            "{{$c}}"
            {{- end }}
            {{- end }}
          ]
        },
        {{- end }}
        {{- if eq (add1 $j) (len $.Values.config.clusters) }}
        {
          "clusters-provider":"{{ $cluster.provider }}",
          "clusters":
          [
            {{- range $i, $c := $cluster.clusters }}
            {{- if lt (add1 $i) (len $cluster.clusters) }}
            "{{$c}}",
            {{- end }}
            {{- if eq (add1 $i) (len $cluster.clusters) }}
            "{{$c}}"
            {{- end }}
            {{- end }}
          ]
        }
        {{- end }}
      {{- end }}
      ]
    }
