replicaCount: 1

image:
  repository: grzegorzpnk/simu
  pullPolicy: Always
  tag: "latest"

workingDir: "/simu"
command: "./simu"
config:
  servicePort: 8888
  nmt:
    endpoint: "http://10.254.185.44"
    port: "32138"
  erc:
    endpoint: "http://10.254.185.44"
    port: "32138"


podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8888
  nodePort: 32138

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
