replicaCount: 1

image:
  repository: pmatysiaq/simu
  pullPolicy: Always
  tag: "latest"

workingDir: "/simu"
command: "./simu"
config:
  servicePort: 8484
  nmt_endpoint: "http://172.18.0.3:32139"
  erc_endpoint: "http://172.18.0.3:32147"
  rl_agent_endpoint: "http://172.18.0.3:32444"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8484
  nodePort: 32144

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
