replicaCount: 1

image:
  repository: grzegorzpnk/simu
  pullPolicy: Always
  tag: "latest"

workingDir: "/simu"
command: "./simu"
config:
  servicePort: 8484
  nmt_endpoint: "http://10.254.185.44:32137"
  erc_endpoint: "http://10.254.185.111:32139"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8484
  nodePort: 32144

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
