apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notificationService.type }}
  ports:
    - port: 8201
      targetPort: 8201
      nodePort: 32201
      name: notification-port-1
    - port: 8202
      targetPort: 8202
      nodePort: 32202
      name: notification-port-2
    - port: 8203
      targetPort: 8203
      nodePort: 32203
      name: notification-port-3
    - port: 8204
      targetPort: 8204
      nodePort: 32204
      name: notification-port-4
    - port: 8205
      targetPort: 8205
      nodePort: 32205
      name: notification-port-5
    - port: 8206
      targetPort: 8206
      nodePort: 32206
      name: notification-port-6
    - port: 8207
      targetPort: 8207
      nodePort: 32207
      name: notification-port-7
    - port: 8208
      targetPort: 8208
      nodePort: 32208
      name: notification-port-8
    - port: 8209
      targetPort: 8209
      nodePort: 32209
      name: notification-port-9
    - port: 8210
      targetPort: 8210
      nodePort: 32210
      name: notification-port-10
    - port: 8211
      targetPort: 8211
      nodePort: 32211
      name: notification-port-11
    - port: 8212
      targetPort: 8212
      nodePort: 32212
      name: notification-port-12
    - port: 8213
      targetPort: 8213
      nodePort: 32213
      name: notification-port-13
    - port: 8214
      targetPort: 8214
      nodePort: 32214
      name: notification-port-14
    - port: 8215
      targetPort: 8215
      nodePort: 32215
      name: notification-port-15
    - port: 8216
      targetPort: 8216
      nodePort: 32216
      name: notification-port-16
    - port: 8217
      targetPort: 8217
      nodePort: 32217
      name: notification-port-17
    - port: 8218
      targetPort: 8218
      nodePort: 32218
      name: notification-port-18
    - port: 8219
      targetPort: 8219
      nodePort: 32219
      name: notification-port-19
    - port: 8220
      targetPort: 8220
      nodePort: 32220
      name: notification-port-20
    - port: 8221
      targetPort: 8221
      nodePort: 32221
      name: notification-port-21
    - port: 8222
      targetPort: 8222
      nodePort: 32222
      name: notification-port-22
    - port: 8223
      targetPort: 8223
      nodePort: 32223
      name: notification-port-23
    - port: 8224
      targetPort: 8224
      nodePort: 32224
      name: notification-port-24
    - port: 8225
      targetPort: 8225
      nodePort: 32225
      name: notification-port-25
    - port: 8226
      targetPort: 8226
      nodePort: 32226
      name: notification-port-26
    - port: 8227
      targetPort: 8227
      nodePort: 32227
      name: notification-port-27
    - port: 8228
      targetPort: 8228
      nodePort: 32228
      name: notification-port-28
    - port: 8229
      targetPort: 8229
      nodePort: 32229
      name: notification-port-29
    - port: 8230
      targetPort: 8230
      nodePort: 32230
      name: notification-port-30
    - port: 8231
      targetPort: 8231
      nodePort: 32231
      name: notification-port-31
    - port: 8232
      targetPort: 8232
      nodePort: 32232
      name: notification-port-32
    - port: 8233
      targetPort: 8233
      nodePort: 32233
      name: notification-port-33
    - port: 8234
      targetPort: 8234
      nodePort: 32234
      name: notification-port-34
    - port: 8235
      targetPort: 8235
      nodePort: 32235
      name: notification-port-35
    - port: 8236
      targetPort: 8236
      nodePort: 32236
      name: notification-port-36
    - port: 8237
      targetPort: 8237
      nodePort: 32237
      name: notification-port-37
    - port: 8238
      targetPort: 8238
      nodePort: 32238
      name: notification-port-38
    - port: 8239
      targetPort: 8239
      nodePort: 32239
      name: notification-port-39
    - port: 8240
      targetPort: 8240
      nodePort: 32240
      name: notification-port-40
    - port: 8241
      targetPort: 8241
      nodePort: 32241
      name: notification-port-41
    - port: 8242
      targetPort: 8242
      nodePort: 32242
      name: notification-port-42
    - port: 8243
      targetPort: 8243
      nodePort: 32243
      name: notification-port-43
    - port: 8244
      targetPort: 8244
      nodePort: 32244
      name: notification-port-44
    - port: 8245
      targetPort: 8245
      nodePort: 32245
      name: notification-port-45
    - port: 8246
      targetPort: 8246
      nodePort: 32246
      name: notification-port-46
    - port: 8247
      targetPort: 8247
      nodePort: 32247
      name: notification-port-47
    - port: 8248
      targetPort: 8248
      nodePort: 32248
      name: notification-port-48
    - port: 8249
      targetPort: 8249
      nodePort: 32249
      name: notification-port-49
    - port: 8250
      targetPort: 8250
      nodePort: 32250
      name: notification-port-50
    - port: 8251
      targetPort: 8251
      nodePort: 32251
      name: notification-port-51
    - port: 8252
      targetPort: 8252
      nodePort: 32252
      name: notification-port-52
    - port: 8253
      targetPort: 8253
      nodePort: 32253
      name: notification-port-53
    - port: 8254
      targetPort: 8254
      nodePort: 32254
      name: notification-port-54
    - port: 8255
      targetPort: 8255
      nodePort: 32255
      name: notification-port-55
    - port: 8256
      targetPort: 8256
      nodePort: 32256
      name: notification-port-56
    - port: 8257
      targetPort: 8257
      nodePort: 32257
      name: notification-port-57
    - port: 8258
      targetPort: 8258
      nodePort: 32258
      name: notification-port-58
    - port: 8259
      targetPort: 8259
      nodePort: 32259
      name: notification-port-59
    - port: 8260
      targetPort: 8260
      nodePort: 32260
      name: notification-port-60
    - port: 8261
      targetPort: 8261
      nodePort: 32261
      name: notification-port-61
    - port: 8262
      targetPort: 8262
      nodePort: 32262
      name: notification-port-62
    - port: 8263
      targetPort: 8263
      nodePort: 32263
      name: notification-port-63
    - port: 8264
      targetPort: 8264
      nodePort: 32264
      name: notification-port-64
    - port: 8265
      targetPort: 8265
      nodePort: 32265
      name: notification-port-65
    - port: 8266
      targetPort: 8266
      nodePort: 32266
      name: notification-port-66
    - port: 8267
      targetPort: 8267
      nodePort: 32267
      name: notification-port-67
    - port: 8268
      targetPort: 8268
      nodePort: 32268
      name: notification-port-68
    - port: 8269
      targetPort: 8269
      nodePort: 32269
      name: notification-port-69
    - port: 8270
      targetPort: 8270
      nodePort: 32270
      name: notification-port-70
    - port: 8271
      targetPort: 8271
      nodePort: 32271
      name: notification-port-71
    - port: 8272
      targetPort: 8272
      nodePort: 32272
      name: notification-port-72
    - port: 8273
      targetPort: 8273
      nodePort: 32273
      name: notification-port-73
    - port: 8274
      targetPort: 8274
      nodePort: 32274
      name: notification-port-74
    - port: 8275
      targetPort: 8275
      nodePort: 32275
      name: notification-port-75
    - port: 8276
      targetPort: 8276
      nodePort: 32276
      name: notification-port-76
    - port: 8277
      targetPort: 8277
      nodePort: 32277
      name: notification-port-77
    - port: 8278
      targetPort: 8278
      nodePort: 32278
      name: notification-port-78
    - port: 8279
      targetPort: 8279
      nodePort: 32279
      name: notification-port-79
    - port: 8280
      targetPort: 8280
      nodePort: 32280
      name: notification-port-80
    - port: 8281
      targetPort: 8281
      nodePort: 32281
      name: notification-port-81
    - port: 8282
      targetPort: 8282
      nodePort: 32282
      name: notification-port-82
    - port: 8283
      targetPort: 8283
      nodePort: 32283
      name: notification-port-83
    - port: 8284
      targetPort: 8284
      nodePort: 32284
      name: notification-port-84
    - port: 8285
      targetPort: 8285
      nodePort: 32285
      name: notification-port-85
    - port: 8286
      targetPort: 8286
      nodePort: 32286
      name: notification-port-86
    - port: 8287
      targetPort: 8287
      nodePort: 32287
      name: notification-port-87
    - port: 8288
      targetPort: 8288
      nodePort: 32288
      name: notification-port-88
    - port: 8289
      targetPort: 8289
      nodePort: 32289
      name: notification-port-89
    - port: 8290
      targetPort: 8290
      nodePort: 32290
      name: notification-port-90
    - port: 8291
      targetPort: 8291
      nodePort: 32291
      name: notification-port-91
    - port: 8292
      targetPort: 8292
      nodePort: 32292
      name: notification-port-92
    - port: 8293
      targetPort: 8293
      nodePort: 32293
      name: notification-port-93
    - port: 8294
      targetPort: 8294
      nodePort: 32294
      name: notification-port-94
    - port: 8295
      targetPort: 8295
      nodePort: 32295
      name: notification-port-95
    - port: 8296
      targetPort: 8296
      nodePort: 32296
      name: notification-port-96
    - port: 8297
      targetPort: 8297
      nodePort: 32297
      name: notification-port-97
    - port: 8298
      targetPort: 8298
      nodePort: 32298
      name: notification-port-98
    - port: 8299
      targetPort: 8299
      nodePort: 32299
      name: notification-port-99
    - port: 8300
      targetPort: 8300
      nodePort: 32300
      name: notification-port-100
    - port: 8301
      targetPort: 8301
      nodePort: 32301
      name: notification-port-101
    - port: 8302
      targetPort: 8302
      nodePort: 32302
      name: notification-port-102
    - port: 8303
      targetPort: 8303
      nodePort: 32303
      name: notification-port-103
    - port: 8304
      targetPort: 8304
      nodePort: 32304
      name: notification-port-104
    - port: 8305
      targetPort: 8305
      nodePort: 32305
      name: notification-port-105
    - port: 8306
      targetPort: 8306
      nodePort: 32306
      name: notification-port-106
    - port: 8307
      targetPort: 8307
      nodePort: 32307
      name: notification-port-107
    - port: 8308
      targetPort: 8308
      nodePort: 32308
      name: notification-port-108
    - port: 8309
      targetPort: 8309
      nodePort: 32309
      name: notification-port-109
    - port: 8310
      targetPort: 8310
      nodePort: 32310
      name: notification-port-110
    - port: 8311
      targetPort: 8311
      nodePort: 32311
      name: notification-port-111
    - port: 8312
      targetPort: 8312
      nodePort: 32312
      name: notification-port-112
    - port: 8313
      targetPort: 8313
      nodePort: 32313
      name: notification-port-113
    - port: 8314
      targetPort: 8314
      nodePort: 32314
      name: notification-port-114
    - port: 8315
      targetPort: 8315
      nodePort: 32315
      name: notification-port-115
    - port: 8316
      targetPort: 8316
      nodePort: 32316
      name: notification-port-116
    - port: 8317
      targetPort: 8317
      nodePort: 32317
      name: notification-port-117
    - port: 8318
      targetPort: 8318
      nodePort: 32318
      name: notification-port-118
    - port: 8319
      targetPort: 8319
      nodePort: 32319
      name: notification-port-119
    - port: 8320
      targetPort: 8320
      nodePort: 32320
      name: notification-port-120
    - port: 8321
      targetPort: 8321
      nodePort: 32321
      name: notification-port-121
    - port: 8322
      targetPort: 8322
      nodePort: 32322
      name: notification-port-122
    - port: 8323
      targetPort: 8323
      nodePort: 32323
      name: notification-port-123
    - port: 8324
      targetPort: 8324
      nodePort: 32324
      name: notification-port-124
    - port: 8325
      targetPort: 8325
      nodePort: 32325
      name: notification-port-125
    - port: 8326
      targetPort: 8326
      nodePort: 32326
      name: notification-port-126
    - port: 8327
      targetPort: 8327
      nodePort: 32327
      name: notification-port-127
    - port: 8328
      targetPort: 8328
      nodePort: 32328
      name: notification-port-128
    - port: 8329
      targetPort: 8329
      nodePort: 32329
      name: notification-port-129
    - port: 8330
      targetPort: 8330
      nodePort: 32330
      name: notification-port-130
    - port: 8331
      targetPort: 8331
      nodePort: 32331
      name: notification-port-131
    - port: 8332
      targetPort: 8332
      nodePort: 32332
      name: notification-port-132
    - port: 8333
      targetPort: 8333
      nodePort: 32333
      name: notification-port-133
    - port: 8334
      targetPort: 8334
      nodePort: 32334
      name: notification-port-134
    - port: 8335
      targetPort: 8335
      nodePort: 32335
      name: notification-port-135
    - port: 8336
      targetPort: 8336
      nodePort: 32336
      name: notification-port-136
    - port: 8337
      targetPort: 8337
      nodePort: 32337
      name: notification-port-137
    - port: 8338
      targetPort: 8338
      nodePort: 32338
      name: notification-port-138
    - port: 8339
      targetPort: 8339
      nodePort: 32339
      name: notification-port-139
    - port: 8340
      targetPort: 8340
      nodePort: 32340
      name: notification-port-140
    - port: 8341
      targetPort: 8341
      nodePort: 32341
      name: notification-port-141
    - port: 8342
      targetPort: 8342
      nodePort: 32342
      name: notification-port-142
    - port: 8343
      targetPort: 8343
      nodePort: 32343
      name: notification-port-143
    - port: 8344
      targetPort: 8344
      nodePort: 32344
      name: notification-port-144
    - port: 8345
      targetPort: 8345
      nodePort: 32345
      name: notification-port-145
    - port: 8346
      targetPort: 8346
      nodePort: 32346
      name: notification-port-146
    - port: 8347
      targetPort: 8347
      nodePort: 32347
      name: notification-port-147
    - port: 8348
      targetPort: 8348
      nodePort: 32348
      name: notification-port-148
    - port: 8349
      targetPort: 8349
      nodePort: 32349
      name: notification-port-149
    - port: 8350
      targetPort: 8350
      nodePort: 32350
      name: notification-port-150
    - port: 8351
      targetPort: 8351
      nodePort: 32351
      name: notification-port-151
    - port: 8352
      targetPort: 8352
      nodePort: 32352
      name: notification-port-152
    - port: 8353
      targetPort: 8353
      nodePort: 32353
      name: notification-port-153
    - port: 8354
      targetPort: 8354
      nodePort: 32354
      name: notification-port-154
    - port: 8355
      targetPort: 8355
      nodePort: 32355
      name: notification-port-155
    - port: 8356
      targetPort: 8356
      nodePort: 32356
      name: notification-port-156
    - port: 8357
      targetPort: 8357
      nodePort: 32357
      name: notification-port-157
    - port: 8358
      targetPort: 8358
      nodePort: 32358
      name: notification-port-158
    - port: 8359
      targetPort: 8359
      nodePort: 32359
      name: notification-port-159
    - port: 8360
      targetPort: 8360
      nodePort: 32360
      name: notification-port-160
    - port: 8361
      targetPort: 8361
      nodePort: 32361
      name: notification-port-161
    - port: 8362
      targetPort: 8362
      nodePort: 32362
      name: notification-port-162
    - port: 8363
      targetPort: 8363
      nodePort: 32363
      name: notification-port-163
    - port: 8364
      targetPort: 8364
      nodePort: 32364
      name: notification-port-164
    - port: 8365
      targetPort: 8365
      nodePort: 32365
      name: notification-port-165
    - port: 8366
      targetPort: 8366
      nodePort: 32366
      name: notification-port-166
    - port: 8367
      targetPort: 8367
      nodePort: 32367
      name: notification-port-167
    - port: 8368
      targetPort: 8368
      nodePort: 32368
      name: notification-port-168
    - port: 8369
      targetPort: 8369
      nodePort: 32369
      name: notification-port-169
    - port: 8370
      targetPort: 8370
      nodePort: 32370
      name: notification-port-170
    - port: 8371
      targetPort: 8371
      nodePort: 32371
      name: notification-port-171
    - port: 8372
      targetPort: 8372
      nodePort: 32372
      name: notification-port-172
    - port: 8373
      targetPort: 8373
      nodePort: 32373
      name: notification-port-173
    - port: 8374
      targetPort: 8374
      nodePort: 32374
      name: notification-port-174
    - port: 8375
      targetPort: 8375
      nodePort: 32375
      name: notification-port-175
    - port: 8376
      targetPort: 8376
      nodePort: 32376
      name: notification-port-176
    - port: 8377
      targetPort: 8377
      nodePort: 32377
      name: notification-port-177
    - port: 8378
      targetPort: 8378
      nodePort: 32378
      name: notification-port-178
    - port: 8379
      targetPort: 8379
      nodePort: 32379
      name: notification-port-179
    - port: 8380
      targetPort: 8380
      nodePort: 32380
      name: notification-port-180
    - port: 8381
      targetPort: 8381
      nodePort: 32381
      name: notification-port-181
    - port: 8382
      targetPort: 8382
      nodePort: 32382
      name: notification-port-182
    - port: 8383
      targetPort: 8383
      nodePort: 32383
      name: notification-port-183
    - port: 8384
      targetPort: 8384
      nodePort: 32384
      name: notification-port-184
    - port: 8385
      targetPort: 8385
      nodePort: 32385
      name: notification-port-185
    - port: 8386
      targetPort: 8386
      nodePort: 32386
      name: notification-port-186
    - port: 8387
      targetPort: 8387
      nodePort: 32387
      name: notification-port-187
    - port: 8388
      targetPort: 8388
      nodePort: 32388
      name: notification-port-188
    - port: 8389
      targetPort: 8389
      nodePort: 32389
      name: notification-port-189
    - port: 8390
      targetPort: 8390
      nodePort: 32390
      name: notification-port-190
    - port: 8391
      targetPort: 8391
      nodePort: 32391
      name: notification-port-191
    - port: 8392
      targetPort: 8392
      nodePort: 32392
      name: notification-port-192
    - port: 8393
      targetPort: 8393
      nodePort: 32393
      name: notification-port-193
    - port: 8394
      targetPort: 8394
      nodePort: 32394
      name: notification-port-194
    - port: 8395
      targetPort: 8395
      nodePort: 32395
      name: notification-port-195
    - port: 8396
      targetPort: 8396
      nodePort: 32396
      name: notification-port-196
    - port: 8397
      targetPort: 8397
      nodePort: 32397
      name: notification-port-197
    - port: 8398
      targetPort: 8398
      nodePort: 32398
      name: notification-port-198
    - port: 8399
      targetPort: 8399
      nodePort: 32399
      name: notification-port-199
    - port: 8400
      targetPort: 8400
      nodePort: 32400
      name: notification-port-200
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}
