mcc: '208'          # Mobile Country Code value
mnc: '93'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000043210'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 127.0.0.10   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 172.16.2.2  # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp:  172.16.3.2  # gNB's local IP address for N3 Interface (Usually same with local IP)
#xnIp:   172.16.5.2
#xnPort: 1632
#xnIpRemote: 172.16.5.1
#xnPortRemote: 1651

# List of AMF address information
amfConfigs:
  - address: 172.16.2.100
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 0x1
    sd: 0x010203

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
