global:
  projectName: free5gc
  userPlaneArchitecture: ulcl  # possible values are "single" and "ulcl"
  uesubnet: 10.1.0.0/16
  n4network:
    name: n4network
    masterIf: ens3
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n3network:
    name: n3network
    masterIf: ens3
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n6network:
    name: n6network
    masterIf: ens3
    subnetIP: 192.168.101.0
    cidr: 24
    gatewayIP: 192.168.101.1
    excludeIP: 192.168.101.254
  n9network:
    name: n9network
    masterIf: ens3
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230

upf1:
  name: upf1
  replicaCount: 1
  image:
    name: towards5gs/free5gc-upf
    pullPolicy: IfNotPresent
  configmap:
    name: upf1-configmap
  volume:
    name: upf1-volume
    mount: /free5gc/config/

  # network paramters
  n9if:  # GTP-U
    ipAddress: 10.100.50.226
  n4if:  # PFCP
    ipAddress: 10.100.50.242
  n6if:  # DN
    ipAddress: 192.168.101.106

  configuration:
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
      ReportCaller: false

      dnn_list:
        - dnn: internet
          cidr: 10.1.0.0/16
          # [optional] apn_list[*].natifname
          natifname: n6

upf2:
  name: upf2
  replicaCount: 1
  image:
    name: towards5gs/free5gc-upf
    pullPolicy: IfNotPresent
  configmap:
    name: upf2-configmap
  volume:
    name: upf2-volume
    mount: /free5gc/config/

  # network paramters
  n9if:  # GTP-U
    ipAddress: 10.100.50.227
  n4if:  # PFCP
    ipAddress: 10.100.50.243
  n6if:  # DN
    ipAddress: 192.168.101.104

  configuration:
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
      ReportCaller: false

      dnn_list:
        - dnn: internet
          cidr: 10.1.0.0/16
          # [optional] apn_list[*].natifname
          natifname: n6

upfb:
  name: upfb
  replicaCount: 1
  image:
    name: towards5gs/free5gc-upf
    pullPolicy: IfNotPresent
  configmap:
    name: upfb-configmap
  volume:
    name: upfb-volume
    mount: /free5gc/config/

  # network paramters
  n3if:  # GTP-U
    ipAddress: 10.100.50.233
  n9if:  # GTP-U
    ipAddress: 10.100.50.225
  n4if:  # PFCP
    ipAddress: 10.100.50.241
  n6if:  # DN
    ipAddress: 192.168.101.101

  configuration:
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
      ReportCaller: false

      dnn_list:
        - dnn: internet
          cidr: 10.1.0.0/16
          # [optional] apn_list[*].natifname
          # natifname: n6
