FROM ubuntu:20.04

CMD ["bash"]

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get -y install \
    && apt-get -y install libsctp1 libsctp-dev lksctp-tools iproute2 tcpdump gcc iputils-ping \
    && apt-get install -y libstdc++6 \
    && apt-get upgrade \
    && apt-get install -y software-properties-common

WORKDIR /ueransim

RUN mkdir config build

COPY ./config/* /ueransim/config/
COPY ./build/* /ueransim/build/

VOLUME [/ueransim/config]

WORKDIR /ueransim/build
