apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    remote_write:
      - url: http://$MIMIR_ENDPOINT:9009/api/v1/push

    scrape_configs:
      - job_name: 'kube-metrics-server'
        honor_timestamps: true
        scheme: http
        static_configs:
          - targets: ['ksm-kube-state-metrics.monitoring.svc.cluster.local:8080']
        metric_relabel_configs:
          - target_label: cluster
            replacement: $MEC_NAME
      
      - job_name: 'metrics-server'
        static_configs:
          - targets: ['metrics-server.kube-system.svc.cluster.local:443']
