apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notificationService.type }}
  ports:
    - port: {{ .Values.notificationService.port }}
      nodePort: {{ .Values.notificationService.nodePort }}
      targetPort: {{ .Values.notificationService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}
