apiVersion: v1
kind: ConfigMap
metadata:
  name: innot-cm
  labels:
    app: {{ include "innot.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
      "model_path_basic": "{{ .Values.config.modelPathBasic }}",
      "model_path_masked": "{{ .Values.config.modelPathMasked }}"
    }