apiVersion: v1
kind: ConfigMap
metadata:
  name: nmt-cm
  labels:
    app: {{ include "nmt.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
      "service-port":"{{ .Values.config.servicePort }}",
      "cluster-controller-endpoint" : "{{ .Values.config.obs.endpoint }}:{{ .Values.config.obs.port }}",
      "edge-provider":"{{ .Values.config.clusterProvider }}",
      "timestamp": {{ .Values.config.timestamp }}
    }
