apiVersion: v1
kind: ConfigMap
metadata:
  name: nmt-cm
  labels:
    app: {{ include "nmt.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
      "service-port":"{{ .Values.config.servicePort }}",
      "edge-provider":"{{ .Values.config.clusterProvider }}",
      "tau":"{{ .Values.config.tau }}",
      "res-min" : {{.Values.config.res_min}},
      "res-max": {{.Values.config.res_max}},
      "max-cell-number" : {{.Values.config.max_cell_number}}
    }