apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmt.fullname" . }}
  labels:
    {{- include "nmt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.servicePort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "nmt.selectorLabels" . | nindent 4 }}
