replicaCount: 1

image:
  repository: pmatysiaq/innot
  pullPolicy: Always
  tag: "latest"

workingDir: "/innot"
command: "./innot"
config:
  amfEndpoint: "http://amf-namf:80/namf-evts/v1/subscriptions"
  servicePort: 8181

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8181
  nodePort: 32137

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
