# memory unit[Mi], cpu unit[m]
---
apiVersion: v1
kind: Pod
metadata:
  name: resource-consumer-2
spec:
  containers:
  - name: app-1
    image: nginx
    resources:
      requests:
        memory: "$REQ_MEMORY"
        cpu: "$REQ_CPU"
