replicaCount: 1

image:
  repository: pmatysiaq/rl-agent
  pullPolicy: Always
  tag: "latest"

workingDir: "/app"
command: "/app/start-server.sh"
config:
  modelPath: "/app/model"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 32444

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
