ProjectName: towards5gs
AdminCloud: orange-cloud
LogicalCluster: orange-lc
ClusterProvider: orange

# Cluster #1
EdgeCluster: edge01
EdgeClusterLabel: LabelEdge
EdgeKubeConfig: ../cfg/ran.config

## Cluster #2
#CloudCluster: cloud01
#CloudClusterLabel: LabelCloud
##CloudKubeConfig: ../cfg/core.config
#CloudKubeConfig: ../cfg/ran.config

# Cluster #3
Free5gcCluster: controller01
Free5gcClusterLabel: LabelController
Free5gcKubeConfig: ../cfg/core.config

# Composite Apps
CompositeApp: free5gc-ca
UeransimCompositeApp: ueransim-ca

# Composite Profile Groups
CompositeProfile: free5gc-composite-profile
UeransimCompositeProfile: ueransim-composite-profile

# Deployment Intent Groups
DeploymentIntent: free5gc-deployment-intent
UeransimDeploymentIntent: ueransim-deployment-intent

# Intents
GenericPlacementIntent: towards5gs-generic-placement

# AMF
AMFAppName: free5gc-amf
AMFAppFile: ../pkg/apps/free5gc-amf-0.1.1.tgz
ProfileAMFAppName: amf-profile
ProfileAMFAppFile: ../pkg/profiles/amf-profile.tar.gz
AMFAppPlacementIntent: amf-placement-intent

# AUSF
AUSFAppName: free5gc-ausf
AUSFAppFile: ../pkg/apps/free5gc-ausf-0.1.1.tgz
ProfileAUSFAppName: ausf-profile
ProfileAUSFAppFile: ../pkg/profiles/ausf-profile.tar.gz
AUSFAppPlacementIntent: ausf-placement-intent

# NRF
NRFAppName: free5gc-nrf
NRFAppFile: ../pkg/apps/free5gc-nrf-0.1.1.tgz
ProfileNRFAppName: nrf-profile
ProfileNRFAppFile: ../pkg/profiles/nrf-profile.tar.gz
NRFAppPlacementIntent: nrf-placement-intent

# NSSF
NSSFAppName: free5gc-nssf
NSSFAppFile: ../pkg/apps/free5gc-nssf-0.1.1.tgz
ProfileNSSFAppName: nssf-profile
ProfileNSSFAppFile: ../pkg/profiles/nssf-profile.tar.gz
NSSFAppPlacementIntent: nssf-placement-intent

# PCF
PCFAppName: free5gc-pcf
PCFAppFile: ../pkg/apps/free5gc-pcf-0.1.1.tgz
ProfilePCFAppName: pcf-profile
ProfilePCFAppFile: ../pkg/profiles/pcf-profile.tar.gz
PCFAppPlacementIntent: pcf-placement-intent

# SMF
SMFAppName: free5gc-smf
SMFAppFile: ../pkg/apps/free5gc-smf-0.1.1.tgz
ProfileSMFAppName: smf-profile
ProfileSMFAppFile: ../pkg/profiles/smf-profile.tar.gz
SMFAppPlacementIntent: smf-placement-intent

# UDM
UDMAppName: free5gc-udm
UDMAppFile: ../pkg/apps/free5gc-udm-0.1.1.tgz
ProfileUDMAppName: udm-profile
ProfileUDMAppFile: ../pkg/profiles/udm-profile.tar.gz
UDMAppPlacementIntent: udm-placement-intent

# UDR
UDRAppName: free5gc-udr
UDRAppFile: ../pkg/apps/free5gc-udr-0.1.1.tgz
ProfileUDRAppName: udr-profile
ProfileUDRAppFile: ../pkg/profiles/udr-profile.tar.gz
UDRAppPlacementIntent: udr-placement-intent

# UPF
UPFAppName: free5gc-upf
UPFAppFile: ../pkg/apps/free5gc-upf-0.1.1.tgz
ProfileUPFAppName: upf-profile
ProfileUPFAppFile: ../pkg/profiles/upf-profile.tar.gz
UPFAppPlacementIntent: upf-placement-intent

# WEBUI
WEBUIAppName: free5gc-webui
WEBUIAppFile: ../pkg/apps/free5gc-webui-0.1.1.tgz
ProfileWEBUIAppName: webui-profile
ProfileWEBUIAppFile: ../pkg/profiles/webui-profile.tar.gz
WEBUIAppPlacementIntent: webui-placement-intent

# UERANSIM
UERANSIMAppName: ueransim
UERANSIMAppFile: ../pkg/apps/ueransim-2.0.12.tgz
ProfileUERANSIMAppName: ueransim-profile
ProfileUERANSIMAppFile: ../pkg/profiles/ueransim-profile.tar.gz
UERANSIMAppPlacementIntent: ueransim-placement-intent

# EMCO Config
HostIP: 10.254.185.70
GacPort:        30493
RsyncPort:      30441
DtcPort:        30483
NpsPort:        30485
OvnPort:        30473
SdsPort:        30486
SfcPort:        30456
SfcClientPort:  30458
HpaplcPort:     30459
HpaacPort:      30443
ClmPort:        30461
DcmPort:        30477
ItsPort:        30487
