global:
  projectName: free5gc
  userPlaneArchitecture: ulcl  # possible values are "single" and "ulcl"
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: "8000"
      nodePort: "30800"
  sbi:
    scheme: http
  smf:
    n4if:
      ipAddress: 10.100.50.244
  n4network:
    name: n4network
    masterIf: ens3
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

# This section can be used to override the default values in the MongoDB chart (remember MongoDB is a subchart of the free5gcControlplane chart since control plane NFs rely on it.
mongodb:
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"

smf:
  configuration:
    configuration: |-
      smfName: SMF
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
        - nsmf-oam
      snssaiInfos:
        - sNssai:
            sst: 1
            sd: 010203
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
            - dnn: internet2
              dns:
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860:8888
        - sNssai:
            sst: 1
            sd: 112233
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
        - sNssai:
            sst: 2
            sd: 112234
          dnnInfos:
            - dnn: internet
              dns:
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
      plmnList: # the list of PLMN IDs that this SMF belongs to (optional, remove this key when unnecessary)
        - mcc: "208" # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: "93" # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      userplane_information:
        up_nodes: # (AN or UPF)
          gNB1:
            type: AN
          UPFB:
            type: UPF
            node_id: 10.100.50.241 # PFCP address
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet
                  - dnn: internet2
              - sNssai:
                  sst: 1
                  sd: 112233
                dnnUpfInfoList:
                  - dnn: internet
                  - dnn: internet2
            interfaces:
              - interfaceType: N3
                endpoints:
                  - 10.100.50.233
                networkInstance: internet
              - interfaceType: N3
                endpoints:
                  - 10.100.50.233
                networkInstance: internet2
              - interfaceType: N9
                endpoints:
                  - 10.100.50.225
                networkInstance: internet
              - interfaceType: N9
                endpoints:
                  - 10.100.50.225
                networkInstance: internet2
          UPF1:
            type: UPF
            node_id: 10.100.50.242 # PFCP address
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet
                    pools:
                    - cidr: 10.1.0.0/17
            interfaces:
              - interfaceType: N9
                endpoints:
                  - 10.100.50.226 # UPF1 N9 address
                networkInstance: internet
          UPF2:
            type: UPF
            node_id: 10.100.50.243 # PFCP address
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet2
                    pools:
                    - cidr: 10.1.128.0/17
            interfaces:
              - interfaceType: N9
                endpoints:
                  - 10.100.50.227 # UPF2 N9 address
                networkInstance: internet2
        links:
          - A: gNB1
            B: UPFB
          - A: UPFB
            B: UPF1
          - A: UPFB
            B: UPF2
      locality: area1 # Name of the location where a set of AMF, SMF and UPFs are located
      ulcl: true

    ueRoutingInfo: |-
      UE1: # Group Name
        members:
        - imsi-208930000000003
        topology: # (Uplink: A->B, Downlink: B->A)
          - A: gNB1
            B: UPFB
          - A: UPFB
            B: UPF2
          - A: UPFB
            B: UPF1
        specificPath:
          - dest: 192.168.101.6/32 # dst DN | this addr of is MEC Host 1
            path: [UPFB, UPF1]
          - dest: 192.168.101.4/32 # dst DN | this addr of is MEC Host 1
            path: [UPFB, UPF2]

    logger:
      SMF:
        debugLevel: info
        ReportCaller: false
      NAS:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      PFCP:
        debugLevel: info
        ReportCaller: false
