apiVersion: v1
kind: Service
metadata:
  name: {{ include "innot.fullname" . }}
  labels:
    {{- include "innot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.servicePort }}
      nodePort: 32137
  selector:
    {{- include "innot.selectorLabels" . | nindent 4 }}
