global:
  multiCluster: false
  #Global network parametes
  n2network:
    name: n2network
    masterIf: ens3
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254
  n3network:
    name: n3network
    masterIf: ens3
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238


projectName: ueransim

ue:
  enabled: true
  name: ue
  replicaCount: 1
  image:
    name: pmatysiaq/ueransim-ue
    pullPolicy: Always
    tag: latest
  configmap:
    name: ue-configmap
  volume:
    name: ue-volume
    mount: /ueransim/config
  command: "./nr-ue -c ../config/ue-config.yaml"  # This is the command that will be launched in the UE container
  # A script that will be run after the UE creation. It may be used to periodically generate traffic
  script: ""
  # script: |-
  #   ping .....

  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext:
    capabilities:
            add: ["NET_ADMIN"]
  resources:
    limits:
      cpu: 240m
      memory: 256Mi
    requests:
      cpu: 240m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  configuration: |-
    supi: "imsi-208930000000003"  # IMSI number
    mcc: '208' # Mobile Country Code value
    mnc: '93' # Mobile Network Code value (2 or 3 digits)
    key: "8baf473f2f8fd09487cccbd7097c6862" # Operator code (OP or OPC) of the UE
    op: "8e27b6af0e692e750f32667a3b14605d" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: "OP" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    amf: '8000' # Authentication Management Field (AMF) value
    imei: '356938035643803' # IMEI number of the device
    imeiSv: '4370816125816151'
    # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false
    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
    sessions:
      - type: "IPv4"
        apn: "internet"
        slice:
          sst: 0x01
          sd: 0x010203
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x010203
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
  
  test:
    connectivity:
      name: ue-connectivity-test
      image: bitnami/kubectl:1.22.0
      configmap:
        name: connectivity-test-configmap
      volume:
        name: connectivity-test-volume
        mount: /scripts
      ttlseconds: 50
